version: "2"
linters:
  default: standard
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - gosec
    - importas
    - intrange
    - misspell
    - modernize
    - tparallel
    - unparam
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      no-inline-comments: true
      no-prefix-comments: false
    gofumpt:
      extra-rules: true
