// Package ssclient provides a Go client for the Archivematica Storage Service
// API.
//
// It wraps the client code generated by kiota-go from the [OpenAPI
// specification].
//
// The package provides a small, domain-oriented wrapper around the generated
// Kiota client for common operations while keeping the generated client
// accessible for advanced use cases.
//
// The public API intentionally abstracts most of the generated request-builder
// surface, but it still uses generated Kiota model types for requests,
// responses, and enums where that keeps the SDK compact and close to the
// service schema.
//
// [OpenAPI specification]: https://artefactual-labs.github.io/ssclient-go/
package ssclient
