// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V2AsyncAsyncItemRequestBuilder builds and executes requests for operations under \api\v2\async\{id}
type V2AsyncAsyncItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV2AsyncAsyncItemRequestBuilderInternal instantiates a new V2AsyncAsyncItemRequestBuilder and sets the default values.
func NewV2AsyncAsyncItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2AsyncAsyncItemRequestBuilder) {
    m := &V2AsyncAsyncItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/async/{id}", pathParameters),
    }
    return m
}
// NewV2AsyncAsyncItemRequestBuilder instantiates a new V2AsyncAsyncItemRequestBuilder and sets the default values.
func NewV2AsyncAsyncItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2AsyncAsyncItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2AsyncAsyncItemRequestBuilderInternal(urlParams, requestAdapter)
}
// EmptyPathSegment the EmptyPathSegment property
// returns a *V2AsyncItemEmptyPathSegmentRequestBuilder when successful
func (m *V2AsyncAsyncItemRequestBuilder) EmptyPathSegment()(*V2AsyncItemEmptyPathSegmentRequestBuilder) {
    return NewV2AsyncItemEmptyPathSegmentRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
