// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V2FileItemDownloadWithChunkNumberItemRequestBuilder builds and executes requests for operations under \api\v2\file\{uuid}\download\{chunkNumber}
type V2FileItemDownloadWithChunkNumberItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV2FileItemDownloadWithChunkNumberItemRequestBuilderInternal instantiates a new V2FileItemDownloadWithChunkNumberItemRequestBuilder and sets the default values.
func NewV2FileItemDownloadWithChunkNumberItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemDownloadWithChunkNumberItemRequestBuilder) {
    m := &V2FileItemDownloadWithChunkNumberItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/file/{uuid}/download/{chunkNumber}", pathParameters),
    }
    return m
}
// NewV2FileItemDownloadWithChunkNumberItemRequestBuilder instantiates a new V2FileItemDownloadWithChunkNumberItemRequestBuilder and sets the default values.
func NewV2FileItemDownloadWithChunkNumberItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemDownloadWithChunkNumberItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2FileItemDownloadWithChunkNumberItemRequestBuilderInternal(urlParams, requestAdapter)
}
// EmptyPathSegment the EmptyPathSegment property
// returns a *V2FileItemDownloadItemEmptyPathSegmentRequestBuilder when successful
func (m *V2FileItemDownloadWithChunkNumberItemRequestBuilder) EmptyPathSegment()(*V2FileItemDownloadItemEmptyPathSegmentRequestBuilder) {
    return NewV2FileItemDownloadItemEmptyPathSegmentRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
