// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588 "go.artefactual.dev/ssclient/kiota/models"
)

// V2FileItemExtract_fileEmptyPathSegmentRequestBuilder builds and executes requests for operations under \api\v2\file\{uuid}\extract_file\
type V2FileItemExtract_fileEmptyPathSegmentRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// V2FileItemExtract_fileEmptyPathSegmentRequestBuilderGetQueryParameters download a single file from the package. Compressed packages may be extracted on demand.
type V2FileItemExtract_fileEmptyPathSegmentRequestBuilderGetQueryParameters struct {
    Relative_path_to_file *string `uriparametername:"relative_path_to_file"`
}
// V2FileItemExtract_fileEmptyPathSegmentRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V2FileItemExtract_fileEmptyPathSegmentRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *V2FileItemExtract_fileEmptyPathSegmentRequestBuilderGetQueryParameters
}
// V2FileItemExtract_fileEmptyPathSegmentRequestBuilderHeadQueryParameters check extracted-file download availability. The current server implementation handles HEAD the same way as GET.
type V2FileItemExtract_fileEmptyPathSegmentRequestBuilderHeadQueryParameters struct {
    Relative_path_to_file *string `uriparametername:"relative_path_to_file"`
}
// V2FileItemExtract_fileEmptyPathSegmentRequestBuilderHeadRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V2FileItemExtract_fileEmptyPathSegmentRequestBuilderHeadRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *V2FileItemExtract_fileEmptyPathSegmentRequestBuilderHeadQueryParameters
}
// NewV2FileItemExtract_fileEmptyPathSegmentRequestBuilderInternal instantiates a new V2FileItemExtract_fileEmptyPathSegmentRequestBuilder and sets the default values.
func NewV2FileItemExtract_fileEmptyPathSegmentRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemExtract_fileEmptyPathSegmentRequestBuilder) {
    m := &V2FileItemExtract_fileEmptyPathSegmentRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/file/{uuid}/extract_file/?relative_path_to_file={relative_path_to_file}", pathParameters),
    }
    return m
}
// NewV2FileItemExtract_fileEmptyPathSegmentRequestBuilder instantiates a new V2FileItemExtract_fileEmptyPathSegmentRequestBuilder and sets the default values.
func NewV2FileItemExtract_fileEmptyPathSegmentRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemExtract_fileEmptyPathSegmentRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2FileItemExtract_fileEmptyPathSegmentRequestBuilderInternal(urlParams, requestAdapter)
}
// Get download a single file from the package. Compressed packages may be extracted on demand.
// returns a AvailabilityResponseable when successful
// returns a AvailabilityResponse error when the service returns a 502 status code
func (m *V2FileItemExtract_fileEmptyPathSegmentRequestBuilder) Get(ctx context.Context, requestConfiguration *V2FileItemExtract_fileEmptyPathSegmentRequestBuilderGetRequestConfiguration)(ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.AvailabilityResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "502": ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.CreateAvailabilityResponseFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.CreateAvailabilityResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.AvailabilityResponseable), nil
}
// Head check extracted-file download availability. The current server implementation handles HEAD the same way as GET.
func (m *V2FileItemExtract_fileEmptyPathSegmentRequestBuilder) Head(ctx context.Context, requestConfiguration *V2FileItemExtract_fileEmptyPathSegmentRequestBuilderHeadRequestConfiguration)(error) {
    requestInfo, err := m.ToHeadRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return err
    }
    err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, nil)
    if err != nil {
        return err
    }
    return nil
}
// ToGetRequestInformation download a single file from the package. Compressed packages may be extracted on demand.
// returns a *RequestInformation when successful
func (m *V2FileItemExtract_fileEmptyPathSegmentRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *V2FileItemExtract_fileEmptyPathSegmentRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToHeadRequestInformation check extracted-file download availability. The current server implementation handles HEAD the same way as GET.
// returns a *RequestInformation when successful
func (m *V2FileItemExtract_fileEmptyPathSegmentRequestBuilder) ToHeadRequestInformation(ctx context.Context, requestConfiguration *V2FileItemExtract_fileEmptyPathSegmentRequestBuilderHeadRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.HEAD, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V2FileItemExtract_fileEmptyPathSegmentRequestBuilder when successful
func (m *V2FileItemExtract_fileEmptyPathSegmentRequestBuilder) WithUrl(rawUrl string)(*V2FileItemExtract_fileEmptyPathSegmentRequestBuilder) {
    return NewV2FileItemExtract_fileEmptyPathSegmentRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
