// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V2FileWithUuItemRequestBuilder builds and executes requests for operations under \api\v2\file\{uuid}
type V2FileWithUuItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// Check_fixity the check_fixity property
// returns a *V2FileItemCheck_fixityRequestBuilder when successful
func (m *V2FileWithUuItemRequestBuilder) Check_fixity()(*V2FileItemCheck_fixityRequestBuilder) {
    return NewV2FileItemCheck_fixityRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// NewV2FileWithUuItemRequestBuilderInternal instantiates a new V2FileWithUuItemRequestBuilder and sets the default values.
func NewV2FileWithUuItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileWithUuItemRequestBuilder) {
    m := &V2FileWithUuItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/file/{uuid}", pathParameters),
    }
    return m
}
// NewV2FileWithUuItemRequestBuilder instantiates a new V2FileWithUuItemRequestBuilder and sets the default values.
func NewV2FileWithUuItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileWithUuItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2FileWithUuItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Delete_aip the delete_aip property
// returns a *V2FileItemDelete_aipRequestBuilder when successful
func (m *V2FileWithUuItemRequestBuilder) Delete_aip()(*V2FileItemDelete_aipRequestBuilder) {
    return NewV2FileItemDelete_aipRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Download the download property
// returns a *V2FileItemDownloadRequestBuilder when successful
func (m *V2FileWithUuItemRequestBuilder) Download()(*V2FileItemDownloadRequestBuilder) {
    return NewV2FileItemDownloadRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// EmptyPathSegment the EmptyPathSegment property
// returns a *V2FileItemEmptyPathSegmentRequestBuilder when successful
func (m *V2FileWithUuItemRequestBuilder) EmptyPathSegment()(*V2FileItemEmptyPathSegmentRequestBuilder) {
    return NewV2FileItemEmptyPathSegmentRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Extract_file the extract_file property
// returns a *V2FileItemExtract_fileRequestBuilder when successful
func (m *V2FileWithUuItemRequestBuilder) Extract_file()(*V2FileItemExtract_fileRequestBuilder) {
    return NewV2FileItemExtract_fileRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Move the move property
// returns a *V2FileItemMoveRequestBuilder when successful
func (m *V2FileWithUuItemRequestBuilder) Move()(*V2FileItemMoveRequestBuilder) {
    return NewV2FileItemMoveRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Pointer_file the pointer_file property
// returns a *V2FileItemPointer_fileRequestBuilder when successful
func (m *V2FileWithUuItemRequestBuilder) Pointer_file()(*V2FileItemPointer_fileRequestBuilder) {
    return NewV2FileItemPointer_fileRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Review_aip_deletion the review_aip_deletion property
// returns a *V2FileItemReview_aip_deletionRequestBuilder when successful
func (m *V2FileWithUuItemRequestBuilder) Review_aip_deletion()(*V2FileItemReview_aip_deletionRequestBuilder) {
    return NewV2FileItemReview_aip_deletionRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
