// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588 "go.artefactual.dev/ssclient/kiota/models"
)

// V2FileItemDownloadItemEmptyPathSegmentRequestBuilder builds and executes requests for operations under \api\v2\file\{uuid}\download\{chunkNumber}\
type V2FileItemDownloadItemEmptyPathSegmentRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// V2FileItemDownloadItemEmptyPathSegmentRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V2FileItemDownloadItemEmptyPathSegmentRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// V2FileItemDownloadItemEmptyPathSegmentRequestBuilderHeadRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V2FileItemDownloadItemEmptyPathSegmentRequestBuilderHeadRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewV2FileItemDownloadItemEmptyPathSegmentRequestBuilderInternal instantiates a new V2FileItemDownloadItemEmptyPathSegmentRequestBuilder and sets the default values.
func NewV2FileItemDownloadItemEmptyPathSegmentRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemDownloadItemEmptyPathSegmentRequestBuilder) {
    m := &V2FileItemDownloadItemEmptyPathSegmentRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/file/{uuid}/download/{chunkNumber}/", pathParameters),
    }
    return m
}
// NewV2FileItemDownloadItemEmptyPathSegmentRequestBuilder instantiates a new V2FileItemDownloadItemEmptyPathSegmentRequestBuilder and sets the default values.
func NewV2FileItemDownloadItemEmptyPathSegmentRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemDownloadItemEmptyPathSegmentRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2FileItemDownloadItemEmptyPathSegmentRequestBuilderInternal(urlParams, requestAdapter)
}
// Get download a LOCKSS package chunk. Successful responses stream the file body.
// returns a AvailabilityResponseable when successful
// returns a AvailabilityResponse error when the service returns a 502 status code
func (m *V2FileItemDownloadItemEmptyPathSegmentRequestBuilder) Get(ctx context.Context, requestConfiguration *V2FileItemDownloadItemEmptyPathSegmentRequestBuilderGetRequestConfiguration)(ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.AvailabilityResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "502": ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.CreateAvailabilityResponseFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.CreateAvailabilityResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.AvailabilityResponseable), nil
}
// Head check LOCKSS package chunk download availability. The current server implementation handles HEAD the same way as GET.
func (m *V2FileItemDownloadItemEmptyPathSegmentRequestBuilder) Head(ctx context.Context, requestConfiguration *V2FileItemDownloadItemEmptyPathSegmentRequestBuilderHeadRequestConfiguration)(error) {
    requestInfo, err := m.ToHeadRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return err
    }
    err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, nil)
    if err != nil {
        return err
    }
    return nil
}
// ToGetRequestInformation download a LOCKSS package chunk. Successful responses stream the file body.
// returns a *RequestInformation when successful
func (m *V2FileItemDownloadItemEmptyPathSegmentRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *V2FileItemDownloadItemEmptyPathSegmentRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToHeadRequestInformation check LOCKSS package chunk download availability. The current server implementation handles HEAD the same way as GET.
// returns a *RequestInformation when successful
func (m *V2FileItemDownloadItemEmptyPathSegmentRequestBuilder) ToHeadRequestInformation(ctx context.Context, requestConfiguration *V2FileItemDownloadItemEmptyPathSegmentRequestBuilderHeadRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.HEAD, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V2FileItemDownloadItemEmptyPathSegmentRequestBuilder when successful
func (m *V2FileItemDownloadItemEmptyPathSegmentRequestBuilder) WithUrl(rawUrl string)(*V2FileItemDownloadItemEmptyPathSegmentRequestBuilder) {
    return NewV2FileItemDownloadItemEmptyPathSegmentRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
