// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588 "go.artefactual.dev/ssclient/kiota/models"
)

// V2FileItemMoveEmptyPathSegmentRequestBuilder builds and executes requests for operations under \api\v2\file\{uuid}\move\
type V2FileItemMoveEmptyPathSegmentRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// V2FileItemMoveEmptyPathSegmentRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V2FileItemMoveEmptyPathSegmentRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewV2FileItemMoveEmptyPathSegmentRequestBuilderInternal instantiates a new V2FileItemMoveEmptyPathSegmentRequestBuilder and sets the default values.
func NewV2FileItemMoveEmptyPathSegmentRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemMoveEmptyPathSegmentRequestBuilder) {
    m := &V2FileItemMoveEmptyPathSegmentRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/file/{uuid}/move/", pathParameters),
    }
    return m
}
// NewV2FileItemMoveEmptyPathSegmentRequestBuilder instantiates a new V2FileItemMoveEmptyPathSegmentRequestBuilder and sets the default values.
func NewV2FileItemMoveEmptyPathSegmentRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemMoveEmptyPathSegmentRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2FileItemMoveEmptyPathSegmentRequestBuilderInternal(urlParams, requestAdapter)
}
// Post move the package to a different storage location.
// returns a []byte when successful
// returns a ErrorEscaped error when the service returns a 400 status code
func (m *V2FileItemMoveEmptyPathSegmentRequestBuilder) Post(ctx context.Context, body ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.PackageMoveRequestable, requestConfiguration *V2FileItemMoveEmptyPathSegmentRequestBuilderPostRequestConfiguration)([]byte, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.CreateErrorEscapedFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.SendPrimitive(ctx, requestInfo, "[]byte", errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.([]byte), nil
}
// ToPostRequestInformation move the package to a different storage location.
// returns a *RequestInformation when successful
func (m *V2FileItemMoveEmptyPathSegmentRequestBuilder) ToPostRequestInformation(ctx context.Context, body ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.PackageMoveRequestable, requestConfiguration *V2FileItemMoveEmptyPathSegmentRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V2FileItemMoveEmptyPathSegmentRequestBuilder when successful
func (m *V2FileItemMoveEmptyPathSegmentRequestBuilder) WithUrl(rawUrl string)(*V2FileItemMoveEmptyPathSegmentRequestBuilder) {
    return NewV2FileItemMoveEmptyPathSegmentRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
