// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V2FileItemDelete_aipRequestBuilder builds and executes requests for operations under \api\v2\file\{uuid}\delete_aip
type V2FileItemDelete_aipRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV2FileItemDelete_aipRequestBuilderInternal instantiates a new V2FileItemDelete_aipRequestBuilder and sets the default values.
func NewV2FileItemDelete_aipRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemDelete_aipRequestBuilder) {
    m := &V2FileItemDelete_aipRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/file/{uuid}/delete_aip", pathParameters),
    }
    return m
}
// NewV2FileItemDelete_aipRequestBuilder instantiates a new V2FileItemDelete_aipRequestBuilder and sets the default values.
func NewV2FileItemDelete_aipRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemDelete_aipRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2FileItemDelete_aipRequestBuilderInternal(urlParams, requestAdapter)
}
// EmptyPathSegment the EmptyPathSegment property
// returns a *V2FileItemDelete_aipEmptyPathSegmentRequestBuilder when successful
func (m *V2FileItemDelete_aipRequestBuilder) EmptyPathSegment()(*V2FileItemDelete_aipEmptyPathSegmentRequestBuilder) {
    return NewV2FileItemDelete_aipEmptyPathSegmentRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
