// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V2FileItemPointer_fileRequestBuilder builds and executes requests for operations under \api\v2\file\{uuid}\pointer_file
type V2FileItemPointer_fileRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV2FileItemPointer_fileRequestBuilderInternal instantiates a new V2FileItemPointer_fileRequestBuilder and sets the default values.
func NewV2FileItemPointer_fileRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemPointer_fileRequestBuilder) {
    m := &V2FileItemPointer_fileRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/file/{uuid}/pointer_file", pathParameters),
    }
    return m
}
// NewV2FileItemPointer_fileRequestBuilder instantiates a new V2FileItemPointer_fileRequestBuilder and sets the default values.
func NewV2FileItemPointer_fileRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemPointer_fileRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2FileItemPointer_fileRequestBuilderInternal(urlParams, requestAdapter)
}
// EmptyPathSegment the EmptyPathSegment property
// returns a *V2FileItemPointer_fileEmptyPathSegmentRequestBuilder when successful
func (m *V2FileItemPointer_fileRequestBuilder) EmptyPathSegment()(*V2FileItemPointer_fileEmptyPathSegmentRequestBuilder) {
    return NewV2FileItemPointer_fileEmptyPathSegmentRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
