// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V2FileItemExtract_fileRequestBuilder builds and executes requests for operations under \api\v2\file\{uuid}\extract_file
type V2FileItemExtract_fileRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV2FileItemExtract_fileRequestBuilderInternal instantiates a new V2FileItemExtract_fileRequestBuilder and sets the default values.
func NewV2FileItemExtract_fileRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemExtract_fileRequestBuilder) {
    m := &V2FileItemExtract_fileRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/file/{uuid}/extract_file", pathParameters),
    }
    return m
}
// NewV2FileItemExtract_fileRequestBuilder instantiates a new V2FileItemExtract_fileRequestBuilder and sets the default values.
func NewV2FileItemExtract_fileRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemExtract_fileRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2FileItemExtract_fileRequestBuilderInternal(urlParams, requestAdapter)
}
// EmptyPathSegment the EmptyPathSegment property
// returns a *V2FileItemExtract_fileEmptyPathSegmentRequestBuilder when successful
func (m *V2FileItemExtract_fileRequestBuilder) EmptyPathSegment()(*V2FileItemExtract_fileEmptyPathSegmentRequestBuilder) {
    return NewV2FileItemExtract_fileEmptyPathSegmentRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
