// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V2FileItemReview_aip_deletionRequestBuilder builds and executes requests for operations under \api\v2\file\{uuid}\review_aip_deletion
type V2FileItemReview_aip_deletionRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV2FileItemReview_aip_deletionRequestBuilderInternal instantiates a new V2FileItemReview_aip_deletionRequestBuilder and sets the default values.
func NewV2FileItemReview_aip_deletionRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemReview_aip_deletionRequestBuilder) {
    m := &V2FileItemReview_aip_deletionRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/file/{uuid}/review_aip_deletion", pathParameters),
    }
    return m
}
// NewV2FileItemReview_aip_deletionRequestBuilder instantiates a new V2FileItemReview_aip_deletionRequestBuilder and sets the default values.
func NewV2FileItemReview_aip_deletionRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemReview_aip_deletionRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2FileItemReview_aip_deletionRequestBuilderInternal(urlParams, requestAdapter)
}
// EmptyPathSegment the EmptyPathSegment property
// returns a *V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder when successful
func (m *V2FileItemReview_aip_deletionRequestBuilder) EmptyPathSegment()(*V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder) {
    return NewV2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
