// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V2FileItemMoveRequestBuilder builds and executes requests for operations under \api\v2\file\{uuid}\move
type V2FileItemMoveRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV2FileItemMoveRequestBuilderInternal instantiates a new V2FileItemMoveRequestBuilder and sets the default values.
func NewV2FileItemMoveRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemMoveRequestBuilder) {
    m := &V2FileItemMoveRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/file/{uuid}/move", pathParameters),
    }
    return m
}
// NewV2FileItemMoveRequestBuilder instantiates a new V2FileItemMoveRequestBuilder and sets the default values.
func NewV2FileItemMoveRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemMoveRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2FileItemMoveRequestBuilderInternal(urlParams, requestAdapter)
}
// EmptyPathSegment the EmptyPathSegment property
// returns a *V2FileItemMoveEmptyPathSegmentRequestBuilder when successful
func (m *V2FileItemMoveRequestBuilder) EmptyPathSegment()(*V2FileItemMoveEmptyPathSegmentRequestBuilder) {
    return NewV2FileItemMoveEmptyPathSegmentRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
