// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V2FileItemCheck_fixityRequestBuilder builds and executes requests for operations under \api\v2\file\{uuid}\check_fixity
type V2FileItemCheck_fixityRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV2FileItemCheck_fixityRequestBuilderInternal instantiates a new V2FileItemCheck_fixityRequestBuilder and sets the default values.
func NewV2FileItemCheck_fixityRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemCheck_fixityRequestBuilder) {
    m := &V2FileItemCheck_fixityRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/file/{uuid}/check_fixity", pathParameters),
    }
    return m
}
// NewV2FileItemCheck_fixityRequestBuilder instantiates a new V2FileItemCheck_fixityRequestBuilder and sets the default values.
func NewV2FileItemCheck_fixityRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemCheck_fixityRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2FileItemCheck_fixityRequestBuilderInternal(urlParams, requestAdapter)
}
// EmptyPathSegment the EmptyPathSegment property
// returns a *V2FileItemCheck_fixityEmptyPathSegmentRequestBuilder when successful
func (m *V2FileItemCheck_fixityRequestBuilder) EmptyPathSegment()(*V2FileItemCheck_fixityEmptyPathSegmentRequestBuilder) {
    return NewV2FileItemCheck_fixityEmptyPathSegmentRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
