// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i53ac87e8cb3cc9276228f74d38694a208cacb99bb8ceb705eeae99fb88d4d274 "strconv"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V2FileItemDownloadRequestBuilder builds and executes requests for operations under \api\v2\file\{uuid}\download
type V2FileItemDownloadRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByChunkNumber gets an item from the go.artefactual.dev/ssclient/kiota.api.v2.file.item.download.item collection
// Deprecated: This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.
// returns a *V2FileItemDownloadWithChunkNumberItemRequestBuilder when successful
func (m *V2FileItemDownloadRequestBuilder) ByChunkNumber(chunkNumber string)(*V2FileItemDownloadWithChunkNumberItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if chunkNumber != "" {
        urlTplParams["chunkNumber"] = chunkNumber
    }
    return NewV2FileItemDownloadWithChunkNumberItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// ByChunkNumberInteger gets an item from the go.artefactual.dev/ssclient/kiota.api.v2.file.item.download.item collection
// returns a *V2FileItemDownloadWithChunkNumberItemRequestBuilder when successful
func (m *V2FileItemDownloadRequestBuilder) ByChunkNumberInteger(chunkNumber int32)(*V2FileItemDownloadWithChunkNumberItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    urlTplParams["chunkNumber"] = i53ac87e8cb3cc9276228f74d38694a208cacb99bb8ceb705eeae99fb88d4d274.FormatInt(int64(chunkNumber), 10)
    return NewV2FileItemDownloadWithChunkNumberItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewV2FileItemDownloadRequestBuilderInternal instantiates a new V2FileItemDownloadRequestBuilder and sets the default values.
func NewV2FileItemDownloadRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemDownloadRequestBuilder) {
    m := &V2FileItemDownloadRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/file/{uuid}/download", pathParameters),
    }
    return m
}
// NewV2FileItemDownloadRequestBuilder instantiates a new V2FileItemDownloadRequestBuilder and sets the default values.
func NewV2FileItemDownloadRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemDownloadRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2FileItemDownloadRequestBuilderInternal(urlParams, requestAdapter)
}
// EmptyPathSegment the EmptyPathSegment property
// returns a *V2FileItemDownloadEmptyPathSegmentRequestBuilder when successful
func (m *V2FileItemDownloadRequestBuilder) EmptyPathSegment()(*V2FileItemDownloadEmptyPathSegmentRequestBuilder) {
    return NewV2FileItemDownloadEmptyPathSegmentRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
