// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588 "go.artefactual.dev/ssclient/kiota/models"
)

// V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder builds and executes requests for operations under \api\v2\file\{uuid}\review_aip_deletion\
type V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewV2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilderInternal instantiates a new V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder and sets the default values.
func NewV2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder) {
    m := &V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/file/{uuid}/review_aip_deletion/", pathParameters),
    }
    return m
}
// NewV2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder instantiates a new V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder and sets the default values.
func NewV2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilderInternal(urlParams, requestAdapter)
}
// Post approve or reject an AIP deletion request associated with this package.
// returns a ReviewAipDeletionSuccessable when successful
// returns a ReviewAipDeletionFailure error when the service returns a 400 status code
// returns a ReviewAipDeletionFailure error when the service returns a 404 status code
func (m *V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder) Post(ctx context.Context, body ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.ReviewAipDeletionRequestable, requestConfiguration *V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilderPostRequestConfiguration)(ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.ReviewAipDeletionSuccessable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.CreateReviewAipDeletionFailureFromDiscriminatorValue,
        "404": ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.CreateReviewAipDeletionFailureFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.CreateReviewAipDeletionSuccessFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.ReviewAipDeletionSuccessable), nil
}
// ToPostRequestInformation approve or reject an AIP deletion request associated with this package.
// returns a *RequestInformation when successful
func (m *V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder) ToPostRequestInformation(ctx context.Context, body ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.ReviewAipDeletionRequestable, requestConfiguration *V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder when successful
func (m *V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder) WithUrl(rawUrl string)(*V2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder) {
    return NewV2FileItemReview_aip_deletionEmptyPathSegmentRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
