// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V2LocationWithUuItemRequestBuilder builds and executes requests for operations under \api\v2\location\{uuid}
type V2LocationWithUuItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV2LocationWithUuItemRequestBuilderInternal instantiates a new V2LocationWithUuItemRequestBuilder and sets the default values.
func NewV2LocationWithUuItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2LocationWithUuItemRequestBuilder) {
    m := &V2LocationWithUuItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/location/{uuid}", pathParameters),
    }
    return m
}
// NewV2LocationWithUuItemRequestBuilder instantiates a new V2LocationWithUuItemRequestBuilder and sets the default values.
func NewV2LocationWithUuItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2LocationWithUuItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2LocationWithUuItemRequestBuilderInternal(urlParams, requestAdapter)
}
// EmptyPathSegment the EmptyPathSegment property
// returns a *V2LocationItemEmptyPathSegmentRequestBuilder when successful
func (m *V2LocationWithUuItemRequestBuilder) EmptyPathSegment()(*V2LocationItemEmptyPathSegmentRequestBuilder) {
    return NewV2LocationItemEmptyPathSegmentRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
