// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V2LocationDefaultWithPurposeItemRequestBuilder builds and executes requests for operations under \api\v2\location\default\{purpose}
type V2LocationDefaultWithPurposeItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV2LocationDefaultWithPurposeItemRequestBuilderInternal instantiates a new V2LocationDefaultWithPurposeItemRequestBuilder and sets the default values.
func NewV2LocationDefaultWithPurposeItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2LocationDefaultWithPurposeItemRequestBuilder) {
    m := &V2LocationDefaultWithPurposeItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/location/default/{purpose}", pathParameters),
    }
    return m
}
// NewV2LocationDefaultWithPurposeItemRequestBuilder instantiates a new V2LocationDefaultWithPurposeItemRequestBuilder and sets the default values.
func NewV2LocationDefaultWithPurposeItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2LocationDefaultWithPurposeItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2LocationDefaultWithPurposeItemRequestBuilderInternal(urlParams, requestAdapter)
}
// EmptyPathSegment the EmptyPathSegment property
// returns a *V2LocationDefaultItemEmptyPathSegmentRequestBuilder when successful
func (m *V2LocationDefaultWithPurposeItemRequestBuilder) EmptyPathSegment()(*V2LocationDefaultItemEmptyPathSegmentRequestBuilder) {
    return NewV2LocationDefaultItemEmptyPathSegmentRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
