// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588 "go.artefactual.dev/ssclient/kiota/models"
)

// V2LocationEmptyPathSegmentRequestBuilder builds and executes requests for operations under \api\v2\location\
type V2LocationEmptyPathSegmentRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
type V2LocationEmptyPathSegmentRequestBuilderGetQueryParameters struct {
    Description *string `uriparametername:"description"`
    Limit *int32 `uriparametername:"limit"`
    Offset *int32 `uriparametername:"offset"`
    Order_by *string `uriparametername:"order_by"`
    Pipeline__uuid *string `uriparametername:"pipeline__uuid"`
    // Deprecated: This property is deprecated, use PurposeAsLocationPurpose instead
    Purpose *string `uriparametername:"purpose"`
    PurposeAsLocationPurpose *ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.LocationPurpose `uriparametername:"purpose"`
    Quota *int32 `uriparametername:"quota"`
    Relative_path *string `uriparametername:"relative_path"`
    Used *int32 `uriparametername:"used"`
    Uuid *string `uriparametername:"uuid"`
}
// V2LocationEmptyPathSegmentRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type V2LocationEmptyPathSegmentRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *V2LocationEmptyPathSegmentRequestBuilderGetQueryParameters
}
// NewV2LocationEmptyPathSegmentRequestBuilderInternal instantiates a new V2LocationEmptyPathSegmentRequestBuilder and sets the default values.
func NewV2LocationEmptyPathSegmentRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2LocationEmptyPathSegmentRequestBuilder) {
    m := &V2LocationEmptyPathSegmentRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/location/{?description,limit,offset,order_by,pipeline__uuid,purpose,quota,relative_path,used,uuid}", pathParameters),
    }
    return m
}
// NewV2LocationEmptyPathSegmentRequestBuilder instantiates a new V2LocationEmptyPathSegmentRequestBuilder and sets the default values.
func NewV2LocationEmptyPathSegmentRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2LocationEmptyPathSegmentRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2LocationEmptyPathSegmentRequestBuilderInternal(urlParams, requestAdapter)
}
// returns a LocationListable when successful
func (m *V2LocationEmptyPathSegmentRequestBuilder) Get(ctx context.Context, requestConfiguration *V2LocationEmptyPathSegmentRequestBuilderGetRequestConfiguration)(ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.LocationListable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.CreateLocationListFromDiscriminatorValue, nil)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ia31f303b98dc4e7292d1559872ed38681eda57e78e48a431654df5b787bc8588.LocationListable), nil
}
// returns a *RequestInformation when successful
func (m *V2LocationEmptyPathSegmentRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *V2LocationEmptyPathSegmentRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *V2LocationEmptyPathSegmentRequestBuilder when successful
func (m *V2LocationEmptyPathSegmentRequestBuilder) WithUrl(rawUrl string)(*V2LocationEmptyPathSegmentRequestBuilder) {
    return NewV2LocationEmptyPathSegmentRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
