// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V2LocationRequestBuilder builds and executes requests for operations under \api\v2\location
type V2LocationRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByUuid gets an item from the go.artefactual.dev/ssclient/kiota.api.v2.location.item collection
// returns a *V2LocationWithUuItemRequestBuilder when successful
func (m *V2LocationRequestBuilder) ByUuid(uuid string)(*V2LocationWithUuItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if uuid != "" {
        urlTplParams["uuid"] = uuid
    }
    return NewV2LocationWithUuItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewV2LocationRequestBuilderInternal instantiates a new V2LocationRequestBuilder and sets the default values.
func NewV2LocationRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2LocationRequestBuilder) {
    m := &V2LocationRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/location", pathParameters),
    }
    return m
}
// NewV2LocationRequestBuilder instantiates a new V2LocationRequestBuilder and sets the default values.
func NewV2LocationRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2LocationRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2LocationRequestBuilderInternal(urlParams, requestAdapter)
}
// DefaultEscaped the default property
// returns a *V2LocationDefaultRequestBuilder when successful
func (m *V2LocationRequestBuilder) DefaultEscaped()(*V2LocationDefaultRequestBuilder) {
    return NewV2LocationDefaultRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// EmptyPathSegment the EmptyPathSegment property
// returns a *V2LocationEmptyPathSegmentRequestBuilder when successful
func (m *V2LocationRequestBuilder) EmptyPathSegment()(*V2LocationEmptyPathSegmentRequestBuilder) {
    return NewV2LocationEmptyPathSegmentRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
