// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// V2PipelineWithUuItemRequestBuilder builds and executes requests for operations under \api\v2\pipeline\{uuid}
type V2PipelineWithUuItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewV2PipelineWithUuItemRequestBuilderInternal instantiates a new V2PipelineWithUuItemRequestBuilder and sets the default values.
func NewV2PipelineWithUuItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2PipelineWithUuItemRequestBuilder) {
    m := &V2PipelineWithUuItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/v2/pipeline/{uuid}", pathParameters),
    }
    return m
}
// NewV2PipelineWithUuItemRequestBuilder instantiates a new V2PipelineWithUuItemRequestBuilder and sets the default values.
func NewV2PipelineWithUuItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*V2PipelineWithUuItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewV2PipelineWithUuItemRequestBuilderInternal(urlParams, requestAdapter)
}
// EmptyPathSegment the EmptyPathSegment property
// returns a *V2PipelineItemEmptyPathSegmentRequestBuilder when successful
func (m *V2PipelineWithUuItemRequestBuilder) EmptyPathSegment()(*V2PipelineItemEmptyPathSegmentRequestBuilder) {
    return NewV2PipelineItemEmptyPathSegmentRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
