// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AsyncTask struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The completed property
    completed *bool
    // The completed_time property
    completed_time *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The created_time property
    created_time *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The error property
    error *string
    // The id property
    id *int32
    // Uniform Resource Identifier, e.g. "/api/v2/space/141593ff-2a27-44a1-9de1-917573fa0f4a/".
    resource_uri *string
    // The result property
    result i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable
    // The updated_time property
    updated_time *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The was_error property
    was_error *bool
}
// NewAsyncTask instantiates a new AsyncTask and sets the default values.
func NewAsyncTask()(*AsyncTask) {
    m := &AsyncTask{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAsyncTaskFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAsyncTaskFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAsyncTask(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AsyncTask) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCompleted gets the completed property value. The completed property
// returns a *bool when successful
func (m *AsyncTask) GetCompleted()(*bool) {
    return m.completed
}
// GetCompletedTime gets the completed_time property value. The completed_time property
// returns a *Time when successful
func (m *AsyncTask) GetCompletedTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.completed_time
}
// GetCreatedTime gets the created_time property value. The created_time property
// returns a *Time when successful
func (m *AsyncTask) GetCreatedTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.created_time
}
// GetError gets the error property value. The error property
// returns a *string when successful
func (m *AsyncTask) GetError()(*string) {
    return m.error
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AsyncTask) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["completed"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCompleted(val)
        }
        return nil
    }
    res["completed_time"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCompletedTime(val)
        }
        return nil
    }
    res["created_time"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedTime(val)
        }
        return nil
    }
    res["error"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetError(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["resource_uri"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetResourceUri(val)
        }
        return nil
    }
    res["result"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.CreateUntypedNodeFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetResult(val.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable))
        }
        return nil
    }
    res["updated_time"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpdatedTime(val)
        }
        return nil
    }
    res["was_error"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWasError(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The id property
// returns a *int32 when successful
func (m *AsyncTask) GetId()(*int32) {
    return m.id
}
// GetResourceUri gets the resource_uri property value. Uniform Resource Identifier, e.g. "/api/v2/space/141593ff-2a27-44a1-9de1-917573fa0f4a/".
// returns a *string when successful
func (m *AsyncTask) GetResourceUri()(*string) {
    return m.resource_uri
}
// GetResult gets the result property value. The result property
// returns a UntypedNodeable when successful
func (m *AsyncTask) GetResult()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable) {
    return m.result
}
// GetUpdatedTime gets the updated_time property value. The updated_time property
// returns a *Time when successful
func (m *AsyncTask) GetUpdatedTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.updated_time
}
// GetWasError gets the was_error property value. The was_error property
// returns a *bool when successful
func (m *AsyncTask) GetWasError()(*bool) {
    return m.was_error
}
// Serialize serializes information the current object
func (m *AsyncTask) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("completed", m.GetCompleted())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("completed_time", m.GetCompletedTime())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("created_time", m.GetCreatedTime())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("error", m.GetError())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("resource_uri", m.GetResourceUri())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("result", m.GetResult())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("updated_time", m.GetUpdatedTime())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("was_error", m.GetWasError())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AsyncTask) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCompleted sets the completed property value. The completed property
func (m *AsyncTask) SetCompleted(value *bool)() {
    m.completed = value
}
// SetCompletedTime sets the completed_time property value. The completed_time property
func (m *AsyncTask) SetCompletedTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.completed_time = value
}
// SetCreatedTime sets the created_time property value. The created_time property
func (m *AsyncTask) SetCreatedTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.created_time = value
}
// SetError sets the error property value. The error property
func (m *AsyncTask) SetError(value *string)() {
    m.error = value
}
// SetId sets the id property value. The id property
func (m *AsyncTask) SetId(value *int32)() {
    m.id = value
}
// SetResourceUri sets the resource_uri property value. Uniform Resource Identifier, e.g. "/api/v2/space/141593ff-2a27-44a1-9de1-917573fa0f4a/".
func (m *AsyncTask) SetResourceUri(value *string)() {
    m.resource_uri = value
}
// SetResult sets the result property value. The result property
func (m *AsyncTask) SetResult(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)() {
    m.result = value
}
// SetUpdatedTime sets the updated_time property value. The updated_time property
func (m *AsyncTask) SetUpdatedTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.updated_time = value
}
// SetWasError sets the was_error property value. The was_error property
func (m *AsyncTask) SetWasError(value *bool)() {
    m.was_error = value
}
type AsyncTaskable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCompleted()(*bool)
    GetCompletedTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetCreatedTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetError()(*string)
    GetId()(*int32)
    GetResourceUri()(*string)
    GetResult()(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)
    GetUpdatedTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetWasError()(*bool)
    SetCompleted(value *bool)()
    SetCompletedTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetCreatedTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetError(value *string)()
    SetId(value *int32)()
    SetResourceUri(value *string)()
    SetResult(value i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.UntypedNodeable)()
    SetUpdatedTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetWasError(value *bool)()
}
