// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type ReviewAipDeletionDecision int

const (
    APPROVE_REVIEWAIPDELETIONDECISION ReviewAipDeletionDecision = iota
    REJECT_REVIEWAIPDELETIONDECISION
)

func (i ReviewAipDeletionDecision) String() string {
    return []string{"approve", "reject"}[i]
}
func ParseReviewAipDeletionDecision(v string) (any, error) {
    result := APPROVE_REVIEWAIPDELETIONDECISION
    switch v {
        case "approve":
            result = APPROVE_REVIEWAIPDELETIONDECISION
        case "reject":
            result = REJECT_REVIEWAIPDELETIONDECISION
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeReviewAipDeletionDecision(values []ReviewAipDeletionDecision) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i ReviewAipDeletionDecision) isMultiValue() bool {
    return false
}
