// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ReviewAipDeletionRequest struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Decision to record. Accepted values are "approve" and "reject".
    decision *ReviewAipDeletionDecision
    // ID of the deletion request event to review.
    event_id *int32
    // Explanation that will be stored alongside the decision.
    reason *string
}
// NewReviewAipDeletionRequest instantiates a new ReviewAipDeletionRequest and sets the default values.
func NewReviewAipDeletionRequest()(*ReviewAipDeletionRequest) {
    m := &ReviewAipDeletionRequest{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateReviewAipDeletionRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateReviewAipDeletionRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewReviewAipDeletionRequest(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ReviewAipDeletionRequest) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDecision gets the decision property value. Decision to record. Accepted values are "approve" and "reject".
// returns a *ReviewAipDeletionDecision when successful
func (m *ReviewAipDeletionRequest) GetDecision()(*ReviewAipDeletionDecision) {
    return m.decision
}
// GetEventId gets the event_id property value. ID of the deletion request event to review.
// returns a *int32 when successful
func (m *ReviewAipDeletionRequest) GetEventId()(*int32) {
    return m.event_id
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ReviewAipDeletionRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["decision"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseReviewAipDeletionDecision)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDecision(val.(*ReviewAipDeletionDecision))
        }
        return nil
    }
    res["event_id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEventId(val)
        }
        return nil
    }
    res["reason"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReason(val)
        }
        return nil
    }
    return res
}
// GetReason gets the reason property value. Explanation that will be stored alongside the decision.
// returns a *string when successful
func (m *ReviewAipDeletionRequest) GetReason()(*string) {
    return m.reason
}
// Serialize serializes information the current object
func (m *ReviewAipDeletionRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetDecision() != nil {
        cast := (*m.GetDecision()).String()
        err := writer.WriteStringValue("decision", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("event_id", m.GetEventId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("reason", m.GetReason())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ReviewAipDeletionRequest) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDecision sets the decision property value. Decision to record. Accepted values are "approve" and "reject".
func (m *ReviewAipDeletionRequest) SetDecision(value *ReviewAipDeletionDecision)() {
    m.decision = value
}
// SetEventId sets the event_id property value. ID of the deletion request event to review.
func (m *ReviewAipDeletionRequest) SetEventId(value *int32)() {
    m.event_id = value
}
// SetReason sets the reason property value. Explanation that will be stored alongside the decision.
func (m *ReviewAipDeletionRequest) SetReason(value *string)() {
    m.reason = value
}
type ReviewAipDeletionRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDecision()(*ReviewAipDeletionDecision)
    GetEventId()(*int32)
    GetReason()(*string)
    SetDecision(value *ReviewAipDeletionDecision)()
    SetEventId(value *int32)()
    SetReason(value *string)()
}
